CREATE TABLE IF NOT EXISTS Items (
	item_id INTEGER PRIMARY KEY,
	category_id INTEGER NOT NULL,
	producer_id INTEGER NOT NULL,
	item_name TEXT NOT NULL ,
	price DECIMAL NOT NULL,
	item_art TEXT NULL
);
CREATE TABLE IF NOT EXISTS Producers (
	producer_id INTEGER PRIMARY KEY,
	producer_name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Categories (
	category_id INTEGER PRIMARY KEY,
	category_name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Stock (
	item_id INTEGER PRIMARY KEY,
	available INTEGER NOT NULL CHECK(available >= 0)
);

INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(1,"Logitech");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(2,"Trust");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(3,"Hama");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(4,"Microsoft");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(5,"Hp");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(6,"Adata");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(7,"WD");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(8,"Seagate");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(9,"LaCie");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(10,"Trascend");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(11,"SanDisk");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(12,"Kingston");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(13,"GoodRam");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(14,"Verbatim");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(15,"Edifier");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(16,"Microlab");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(17,"Genius");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(18,"Esperanza");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(19,"Razer");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(20,"Plantronics");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(21,"Antilion");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(22,"Redragon");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(23,"Oem");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(24,"Asus");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(25,"Gembird");
INSERT OR IGNORE INTO Producers (producer_id, producer_name) VALUES(26,"Canyon");

INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(1,"Mouse");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(2,"Tastaturi");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(3,"HDD");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(4,"SSD");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(5,"USB");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(6,"Boxe");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(7,"Casti");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(8,"Microfoane");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(9,"Mousepad");
INSERT OR IGNORE INTO Categories (category_id, category_name) VALUES(10,"CamereWe");

INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(1,1,1,"Mouse Logitech M185, USB, Swift Grey",49.99,"Mouse Logitech M185, USB, Swift Grey.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(2,1,1,"Mouse gaming wireless Logitech G502 LightSpeed",559.99,"Mouse gaming wireless Logitech G502 LightSpeed.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(3,1,1,"Mouse wireless Logitech Marathon M705, USB, Silver",199.99,"Mouse wireless Logitech Marathon M705, USB, Silver.png");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(4,1,2,"Mouse gaming Trust GXT 138 X-Ray, Negru",109.99,"Mouse gaming Trust GXT 138 X-Ray, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(5,1,2,"Mouse wireless Trust Yvi FX, Roz",29.99,"Mouse wireless Trust Yvi FX, Roz.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(6,1,3,"Mouse gaming Hama uRage Illuminated, Negru",49.99,"Mouse gaming Hama uRage Illuminated, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(7,1,4,"Mouse Microsoft Mobile 3600, Bluetooth, Albastru",134.99,"Mouse Microsoft Mobile 3600, Bluetooth, Albastru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(8,1,5,"Mouse HP Premium, Negru",79.99,"Mouse HP Premium, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(9,2,1,"Tastatura Logitech K270, Wireless, Negru",159.99,"Tastatura Logitech K270, Wireless, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(10,2,1,"Tastatura gaming mecanica Logitech G512, Iluminare RGB, Switch GX Blue, US INT'L , Carbon",519.99,"Tastatura gaming mecanica Logitech G512, Iluminare RGB, Switch GX Blue, US INT'L , Carbon.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(11,2,2,"Tastatura gaming Trust GXT 830 RW-C Avonn, iluminare rainbow, Camo",99.99,"Tastatura gaming Trust GXT 830 RW-C Avonn, iluminare rainbow, Camo.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(12,2,2,"Tastatura Trust Primon, US Layout, USB, Negru",39.99,"Tastatura Trust Primon, US Layout, USB, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(13,2,3,"Tastatura wireless Hama Cortino, Negru",49.99,"Tastatura wireless Hama Cortino, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(14,2,3,"Tastatura Hama uRage Cyberboard, Negru",192.53,"Tastatura Hama uRage Cyberboard, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(15,2,4,"Tastatura Microsoft Wired Keyboard 600, USB, Negru",62.99,"Tastatura Microsoft Wired Keyboard 600, USB, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(16,2,5,"Tastatura HP Pavilion 300, Negru",119.99,"Tastatura HP Pavilion 300, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(17,3,6,"HDD extern ADATA HV620S, 2TB, 2.5, USB 3.1, Negru",289.98,"HDD extern ADATA HV620S, 2TB, 2.5, USB 3.1, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(18,3,6,"HDD Extern ADATA Durable HD330 1TB, Shock Sensor",235.99,"HDD Extern ADATA Durable HD330 1TB, Shock Sensor.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(19,3,7,"HDD extern WD Elements Portable, 1TB, 2.5, USB 3.0",209.99,"HDD extern WD Elements Portable, 1TB, 2.5, USB 3.0.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(20,3,8,"HDD extern Seagate Expansion Portable 1TB, 2.5",204.98,"HDD extern Seagate Expansion Portable 1TB, 2.5.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(21,3,8,"HDD extern Seagate Expansion Portable 2TB, 2.5",274.99,"HDD extern Seagate Expansion Portable 2TB, 2.5.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(22,3,9,"HDD extern LaCie Rugged Mini, 2TB, 2.5, USB 3.0",409.99,"HDD extern LaCie Rugged Mini, 2TB, 2.5, USB 3.0.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(23,3,9,"HDD Extern LaCie Mobile Drive, 2TB, 2.5, USB 3.1",428.4,"HDD Extern LaCie Mobile Drive, 2TB, 2.5, USB 3.1.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(24,3,10,"HDD extern Transcend StoreJet M3, 1TB, 2.5, USB 3.0, Negru",365.01,"HDD extern Transcend StoreJet M3, 1TB, 2.5, USB 3.0, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(25,4,6,"SSD extern ADATA SC685, 500GB Type-C, multiplatform, cable Type-C",345.99,"SSD extern ADATA SC685, 500GB Type-C, multiplatform, cable Type-C.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(26,4,6,"SSD extern ADATA Durable SD700, 1TB USB 3.1, Negru",606.24,"SSD extern ADATA Durable SD700, 1TB USB 3.1, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(27,4,7,"SD Extern WD My Passport 512GB, USB 3.1",375.21,"SD Extern WD My Passport 512GB, USB 3.1.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(28,4,8,"SSD Extern Seagate Expansion 500GB, USB 3.0, Negru",365.99,"SSD Extern Seagate Expansion 500GB, USB 3.0, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(29,4,8,"SSD Extern Seagate Game Drive Xbox 1TB, USB 3.0",1226.99,"SSD Extern Seagate Game Drive Xbox 1TB, USB 3.0.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(30,4,9,"SSD Extern LaCie Portable 2TB, USB 3.1 Type-C",1652.01,"SSD Extern LaCie Portable 2TB, USB 3.1 Type-C.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(31,4,10,"SSD Extern Transcend ESD240C 120GB USB 3.1 Gen 2 Type C Silver",304.01,"SSD Extern Transcend ESD240C 120GB USB 3.1 Gen 2 Type C Silver.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(32,4,10,"SSD Extern Transcend ESD240C 480GB USB 3.1 Gen 2 Type C Silver",365.99,"SSD Extern Transcend ESD240C 480GB USB 3.1 Gen 2 Type C Silver.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(33,5,11,"Memorie USB Sandisk Cruzer Glide 32GB, USB 3.0",31.99,"Memorie USB Sandisk Cruzer Glide 32GB, USB 3.0.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(34,5,11,"Memorie USB SanDisk Ultra Fit 16 GB, USB 3.1, Negru",21.99,"Memorie USB SanDisk Ultra Fit 16 GB, USB 3.1, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(35,5,6,"Memorie USB ADATA UV320, 32GB, USB 3.2 Gen 1",18.46,"Memorie USB ADATA UV320, 32GB, USB 3.2 Gen 1.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(36,5,12,"Memorie USB Kingston DataTraveler 100 G3, 32GB",22.37,"Memorie USB Kingston DataTraveler 100 G3, 32GB.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(37,5,13,"Stick USB UTS2, 64GB, USB 2.0, Negru",34.99,"Stick USB UTS2, 64GB, USB 2.0, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(38,5,14,"Stick USB Drive 2.0, 256GB, Negru",137.01,"Stick USB Drive 2.0, 256GB, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(39,6,15,"Boxe Edifier 2.1 150W S350DB, bluetooth, telecomanda, brown",949.99,"Boxe Edifier 2.1 150W S350DB, bluetooth, telecomanda, brown.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(40,6,15,"Boxe Edifier 2.0 R1700BT-BR, 66W, Bluetooth, Telecomanda, Maro",529.99,"Boxe Edifier 2.0 R1700BT-BR, 66W, Bluetooth, Telecomanda, Maro.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(41,6,16,"Boxe Microlab 2.0 B-77, 48W",360.85,"Boxe Microlab 2.0 B-77, 48W.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(42,6,2,"Boxe Trust Tytan 2.1, 60W, Negru",269.99,"Boxe Trust Tytan 2.1, 60W, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(43,6,17,"Boxe Genius 2.0 SP-HF180, 6W, Negru",63.17,"Boxe Genius 2.0 SP-HF180, 6W, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(44,6,17,"Boxe Genius 5.1 SW-HF5.1 4600, 125W, Telecomanda",569.99,"Boxe Genius 5.1 SW-HF5.1 4600, 125W, Telecomanda.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(45,6,18,"Boxe 2.0 GIOCOSSO, compatibile PC si laptop",38.08,"Boxe 2.0 GIOCOSSO, compatibile PC si laptop.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(46,6,18,"Boxe PC 2X3W 2.0 BEAT",47.3,"Boxe PC 2X3W 2.0 BEAT.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(47,7,19,"Casti Gaming Razer Kraken Tournament Edition, THX",349.22,"Casti Gaming Razer Kraken Tournament Edition, THX.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(48,7,19,"Casti gaming wireless Razer BlackShark V2 Pro, 2.4GHz HyperSpeed, THX Certified",899.99,"Casti gaming wireless Razer BlackShark V2 Pro, 2.4GHz HyperSpeed, THX Certified.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(49,7,19,"asti gaming Razer BlackShark V2 + USB SoundCard, Multiplatforma",509.96,"asti gaming Razer BlackShark V2 + USB SoundCard, Multiplatforma.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(50,7,1,"Casti gaming wireless Logitech G733, ultrausoare",839.58,"Casti gaming wireless Logitech G733, ultrausoare.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(51,7,1,"Casti gaming Logitech G432, surround 7.1, multiplatforma, Negru",259.99,"Casti gaming Logitech G432, surround 7.1, multiplatforma, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(52,7,2,"Casti gaming Trust GXT 444 Wayman Pro, Negru",259.99,"Casti gaming Trust GXT 444 Wayman Pro, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(53,7,20,"Casti Gaming Plantronics RIG 400PC",209.99,"Casti Gaming Plantronics RIG 400PC.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(54,7,20,"Casca Call Center Plantronics Blackwire C3220, USB-C, Binaural",279.99,"Casca Call Center Plantronics Blackwire C3220, USB-C, Binaural.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(55,7,3,"Casti on ear Hama HK5618 cu adaptor jack 6.35mm inclus",59.12,"Casti on ear Hama HK5618 cu adaptor jack 6.35mm inclus.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(56,7,3,"Casti Thomson HED1105BL On-Ear Kids -pentru copii, HAMA-132467",66.97,"Casti Thomson HED1105BL On-Ear Kids -pentru copii, HAMA-132467.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(57,8,2,"Microfon Trust Mico 2020, USB, stand Tripod",54.99,"Microfon Trust Mico 2020, USB, stand Tripod.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(58,8,3,"Microfon gaming Hama uRage Stream 400 Plus, Negru",123.99,"Microfon gaming Hama uRage Stream 400 Plus, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(59,8,19,"Microfon gaming Razer Seiren X, Negru",419.99,"Microfon gaming Razer Seiren X, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(60,8,21,"Microfon Antlion ModMic USB, switch UniOmni directional",463.99,"Microfon Antlion ModMic USB, switch UniOmni directional.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(61,8,22,"Microfon Redragon GM200, omnidirectional, stativ inclus, USB",119.99,"Microfon Redragon GM200, omnidirectional, stativ inclus, USB.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(62,8,22,"Microfon Redragon Blazar, cu stand, Negru",299.11,"Microfon Redragon Blazar, cu stand, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(63,9,23,"Mouse Pad - Harta lumii 90 x 40 cm",49.98,"Mouse Pad - Harta lumii 90 x 40 cm.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(64,9,23,"Mousepad, XXL, gaming si birou, 800 x 300 x 3mm",41.3,"Mousepad, XXL, gaming si birou, 800 x 300 x 3mm.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(65,9,3,"Mousepad mini Hama Ergonomic, Negru",69.99,"Mousepad mini Hama Ergonomic, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(66,9,19,"Mousepad gaming Razer Sphex V2",97.75,"Mousepad gaming Razer Sphex V2.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(67,9,19,"Mousepad Gaming Razer Firefly, Customizable chroma lighting",349.86,"Mousepad Gaming Razer Firefly, Customizable chroma lighting.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(68,9,24,"Mousepad gaming ASUS ROG Sheath BLK LTD, dimensiuni foarte mari, baza",336.76,"Mousepad gaming ASUS ROG Sheath BLK LTD, dimensiuni foarte mari, baza.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(69,9,25,"Mousepad, Gembird MP-S-BK, cauciucat, negru",3.5,"Mousepad, Gembird MP-S-BK, cauciucat, negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(70,9,25,"Mouse pad Gembird Black cauciucat",4.61,"Mouse pad Gembird Black cauciucat.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(71,10,1,"Camera web Logitech HD Pro C920, Full HD, Negru",549.25,"Camera web Logitech HD Pro C920, Full HD, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(72,10,17,"Camera web Genius WideCam F100, Full HD, Negru",232.05,"Camera web Genius WideCam F100, Full HD, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(73,10,17,"Camera web Genius QCam 6000, Full HD, Negru",198.73,"Camera web Genius QCam 6000, Full HD, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(74,10,2,"Camera web Trust Trino, HD",119.99,"Camera web Trust Trino, HD.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(75,10,4,"Camera Web Microsoft LifeCam HD-3000, HD, Negru",159.85,"Camera Web Microsoft LifeCam HD-3000, HD, Negru.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(76,10,26,"Camera Web Canyon CNE-CWC1, BlackSilver",48.99,"Camera Web Canyon CNE-CWC1, BlackSilver.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(77,10,26,"Webcam Canyon CWC5, FullHD 1080p",199.99,"Webcam Canyon CWC5, FullHD 1080p.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(78,10,26,"Camera web Canyon CNS-CWC6N, 2K QHD, USB, Tripod inclus",249.99,"Camera web Canyon CNS-CWC6N, 2K QHD, USB, Tripod inclus.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(79,10,26,"Camera Web Canyon CNE-CWC3, Full HD, BlackSilver",105.65,"Camera Web Canyon CNE-CWC3, Full HD, BlackSilver.jpg");
INSERT OR IGNORE INTO Items (item_id,category_id,producer_id,item_name,price,item_art) VALUES(80,10,4,"Camera Web Microsoft LifeCam Studio for Business",449.55,"Camera Web Microsoft LifeCam Studio for Business.jpg");

INSERT OR IGNORE INTO Stock (item_id, available) VALUES(1,192);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(2,192);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(3,174);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(4,178);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(5,115);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(6,126);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(7,192);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(8,199);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(9,149);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(10,106);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(11,100);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(12,126);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(13,168);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(14,139);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(15,192);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(16,162);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(17,177);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(18,172);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(19,135);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(20,139);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(21,128);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(22,106);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(23,118);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(24,190);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(25,184);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(26,107);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(27,190);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(28,180);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(29,168);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(30,111);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(31,174);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(32,188);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(33,107);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(34,138);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(35,102);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(36,182);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(37,128);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(38,118);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(39,190);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(40,112);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(41,168);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(42,128);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(43,134);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(44,128);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(45,153);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(46,117);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(47,160);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(48,124);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(49,119);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(50,105);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(51,168);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(52,193);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(53,170);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(54,163);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(55,167);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(56,140);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(57,156);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(58,134);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(59,183);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(60,133);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(61,105);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(62,195);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(63,184);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(64,187);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(65,105);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(66,135);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(67,165);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(68,158);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(69,199);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(70,154);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(71,122);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(72,161);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(73,119);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(74,153);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(75,198);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(76,195);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(77,189);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(78,136);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(79,132);
INSERT OR IGNORE INTO Stock (item_id, available) VALUES(80,182);
